### ISSUE TITLE
Bug in normalization

### ISSUE THREAD

**Issue by ahmdtaha** [JeanKossaifi/python-hog#1]
Inside def normalise_histogram function

 for x in range(**n_blocksy**):
            for y in range(**n_blocksx**):

I think it should be

 for x in range(**n_blocksx**):
            for y in range(**n_blocksy**):

If you try non-square images, the original code breaks

**Comment by JeanKossaifi** [comment]
Absolutely, my bad!
Would you like to make a small pull-request fixing it?

**Comment by ahmdtaha** [comment]
yes, sure

**Comment by JeanKossaifi** [comment]
Awesome, thanks!
Will leave this open until fixed :)

**Comment by JeanKossaifi** [comment]
Fixed by #2
