### ISSUE TITLE
Normalization L2 Norm 

### ISSUE THREAD

**Issue by ahmdtaha** [JeanKossaifi/python-hog#3]
When you compute L2 Norm you do

np.sqrt(normalised_blocks[y, x, :].sum()**2 + eps)

I think it should be
np.sqrt((normalised_blocks[y, x, :]****2).sum()** + eps)

Originally, you sum, square and finally root
It should be square, sum and finally root.

**Comment by JeanKossaifi** [comment]
Right again @ahmdtaha ! I added the normalisation function but did not use it in practice... 
Want to open another pull request? :)

**Comment by JeanKossaifi** [comment]
Thanks @ahmdtaha for reporting fixed by 0a4496c3ae5516951f7357d4e88a326c8700f2cd.
